const {chromium}=require('playwright');
const fs=require('fs');
setTimeout(()=>{console.error('SMOKE TIMEOUT after 85 seconds');process.exit(2);},85000).unref();
const assert=require('assert');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome',args:['--no-sandbox','--enable-webgl','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']});
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});
 const page=await context.newPage();const errors=[];
 page.on('pageerror',error=>{errors.push(String(error));console.log('PAGEERROR',String(error))});
 page.on('console',message=>{if(message.type()==='error')console.log('CONSOLE',message.text())});
 fs.mkdirSync('test-results',{recursive:true});
 console.log('Launching Chrome at 390×844');
 await page.goto('http://127.0.0.1:8765/studio.html',{waitUntil:'domcontentloaded',timeout:30000});
 console.log('Navigation done. status:',await page.locator('#status').innerText());
 await page.waitForFunction(()=>document.getElementById('status').textContent.includes('3D ready'),null,{timeout:20000}).catch(async()=>{console.log('STATUS',await page.locator('#status').innerText());});
 const status=await page.locator('#status').innerText();
 assert(status.includes('3D ready'),'Real glTF model did not load: '+status);
 console.log('PASS 3D model loaded',status);
 await page.locator('#demo').click();
 await page.waitForFunction(()=>document.getElementById('status').textContent==='Voice analyzed',{timeout:20000});
 console.log('PASS demo audio decoded');
 const speech=await page.locator('#speechCount').innerText();
 await page.locator('[data-tab="direct"]').click();
 const count=await page.locator('#gestureCount').innerText();
 assert(+count>=1,'Missing gesture cues');
 console.log('PASS timeline generated','speech',speech,'gestures',count);
 await page.locator('[data-pose="present"]').click();
 await page.locator('[data-tab="create"]').click();
 await page.screenshot({path:'test-results/robot-studio-iphone.png',fullPage:true});
 await page.locator('#play').click();
 await page.waitForTimeout(700);
 const elapsed=await page.locator('#clock').innerText();
 const audioPosition=await page.locator('#audio').evaluate(el=>el.currentTime);
 assert(audioPosition>0.2,'Audio playback is not running: '+audioPosition+' / '+elapsed);
 console.log('PASS audio playback',audioPosition.toFixed(3)+'s',elapsed);
 await page.locator('#play').click();
 await page.locator('[data-tab="export"]').click();
 await page.locator('#downloadPlan').click();
 console.log('PASS export controls');
 assert(!errors.length,'Browser page exceptions: '+errors.join('; '));
 await browser.close();
 console.log('ALL MOBILE 3D BROWSER SMOKE TESTS PASSED');
})().catch(e=>{console.error('SMOKE FAILED',e.stack||e);process.exit(1);});
